# Site settings
title: Try and try until you succeed
header-img: img/home-bg.png
email: anu.konatala@gmail.com
copyright_name: anukonatala
description: > # this means to ignore newlines until "baseurl:"
  My Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  anukonatala
learn_profile: anukonatala
email_username: anu.konatala@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
